config/routes.rb
ShrimpTag::Application.routes.draw do
  get '/onePost' => 'news#edit'
  get '/example' => 'news#example'
  post '/submit' => 'news#update'#, :as => :bb
  get '/ended' => 'news#ended'

  root :to => 'news#example'

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :desc, :fbcm, :fbid, :title
  serialize :fbcm, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

	before_filter :redirect_to_ended, :except => :ended

	def edit
		@oneNews = News.where('"sum"<3 AND "lastModified"<?',Time.now-1200).order('sum').first
		@oneNews.lastModified = Time.now
		@oneNews.save
	end
	def update
		# puts params[:newsid]
		@target = News.where('id = ?',params[:newsid].to_i)[0]
		@target.lastModified = Time.new(1990,1,1)
		if params[:label] != 'donotKnow'
			@target.sum = @target.sum + 1
			# puts @target.id,": ",@target.sum
			if params[:label] == 'Shrimp'
				@target.shrimpSum = @target.shrimpSum + 1
			end
			@target.save
		end
		redirect_to onePost_path
	end
	def example
	end

	def ended
		render 'end'
	end

private
	def redirect_to_ended
		redirect_to ended_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShrimpTag</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application" %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag "application" %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41365599-1', 'herokuapp.com');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/news/edit.html.erb
<div class="span9">

<table>
	<tr>
		<td>
			<h3><%= @oneNews['title'] %></h3>
		</td>
	</tr>
	<tr class="break"></tr>
	<tr>
		<td>
			<%= simple_format @oneNews['desc'] %>
		</td>
	</tr>
	<tr class="break"></tr>
	<tr>
		<td><h4>Comments:</h4></td>
	</tr>
	<% for $comment in @oneNews['fbcm'].each do%>
		<tr class="oneComment">
			<td>
			<p><%= $comment %></p>
			</td>
		</tr>
	<% end %>
</table>
</div>

<%= form_tag submit_path, :method => 'post', :class=>'formbtn' do%>
	<input type="text" value="<%= @oneNews.id %>" name="newsid" style="display:none">
	<%= button_tag :蝦, :'data-value'=>'Shrimp', :class=>"btn btn-danger" %>
	<%= button_tag :不蝦, :'data-value'=>'notShrimp', :class=>"btn btn-success" %>
	<%= button_tag :我不知道, :'data-value'=>'donotKnow', :class => 'btn btn-inverse' %>
<% end %>

app/views/news/end.html.erb
<div class="exampleMain">
	<div class="span10">
  	<p class="end">
  		已經蒐集到足夠的樣本數，所以標記已經結束囉 :)</br>
  		但是仍然謝謝你！</br>
      </br>
    </p>
    <h4>P 幣將於 6/20 開始發放，感謝大家的參與！</h4>
  </div>
</div>

app/views/news/example.html.erb
<div class="container">
<div class="row">
	<div class="span10 offset1">
		<header class="hero-unit">
			<h2><span class="text-error">蝦新聞</span>標記系統</h2>
			<p>
			此篇問卷主要是請大家幫忙評論一篇新聞「蝦」或「不蝦」。
			純粹學術用途，也不會記名，請大家放心。</p>
			<p>
		</header>

		<div class="row">
			<div class="span7">
				<h3>啥毀係蝦？</h3>
				1. 讓讀者感覺<strong class="text-info">此篇新聞沒有存在之必要</strong>，讓人有「這樣也一篇」之感。</br>
				2. <strong class="text-info">新聞內容錯誤或是荒謬</strong>，讓人覺得記者沒搞清楚狀況未求證，素質低落待加強。</br>
				3. 任何讓你感到「<strong class="text-info">這好蝦！</strong>」的新聞。</br>
				</p>
			</div>
			<div class="span3">
				<%= image_tag 'shrimp.jpg', :style => 'margin-top: 55px' %>
			</div>
		</div>

		<p>
		下面是兩篇蝦新聞範例
		（當然，新聞如此多，大家各自主觀認定即可）
		</p>
		<p>
		<div class="row">
			<div class="span5">
				<%= link_to( image_tag("ex1.png"), "http://goo.gl/qYDvw", :target => '_blank', :class => 'thumbnail' )%>
				<p>（從留言可以看出報導與事實不符，記者看圖說故事）</p>
			</div>
			<div class="span5">
				<%= link_to( image_tag("ex2.png"), "http://goo.gl/hc8Zw", :target => '_blank', :class => 'thumbnail' )%>
			</div>
		</div>
		</p>

		<h3>
			評論方式
		</h3>
		<p>
			點選進入網站按鈕之後，會看到每一頁都是一篇新聞，按照<span class="text-info">標題、內文、評論</span>（包含fb評論以及若是有被轉到版上的推噓文）</br>
			請在左方三個大大地按鈕中選擇你覺得此篇新聞給你的感受如何：<span class="text-alert">蝦</span> / <span class="text-success">不蝦</span> / <span class="muted">我不知道</span>。
			（若無法評論請選「<span class="muted">我不知道</span>」，但就無法計入有效題數）</br>
			評論後頁面會自動跳出下一則新聞。</br>
			有效題數<strong class="text-info">五題</strong>可以到<a href="http://goo.gl/jjTcT" target="_blank">這裡</a>填寫ID，題數認定採自由心證 :)</br>
			問卷結束之後會抽一百二十人各100p，總共發一萬二批幣！
		</p>
		<p>
			你的每一篇評論都對我們相當重要！
		</p>
		<p>
		<%= link_to('進入網站', onePost_path, :class=>"btn btn-success enter")%>
		</p>
	</div>
</div>
</div>